name: adminaqlanstore
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_storage:
  image_picker:
  http_parser:
  path:
  mime:
  uuid:
  supabase_flutter:
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.1.10
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/favicon-32x32.png
    - assets/aqlan.png

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

    - family: RobotoLocal
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/aqlan.png"

flutter_native_splash:
  color: "#ffffff"  # لون الخلفية (يمكن تغييره)
  image: assets/aqlan.png
  branding: null
  color_dark: "#000000"
  image_dark: assets/aqlan.png

  android: true
  ios: true
  web: true
  windows: true

  android_12:
    image: assets/aqlan.png
    color: "#ffffff"
    icon_background_color: "#ffffff"